// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Pantalla1Bienvenido
void ui_Pantalla1Bienvenido_screen_init(void);
void ui_event_Pantalla1Bienvenido(lv_event_t * e);
lv_obj_t * ui_Pantalla1Bienvenido;
void ui_event_TextoBienvenido(lv_event_t * e);
lv_obj_t * ui_TextoBienvenido;

// SCREEN: ui_Pantalla2IngHora
void ui_Pantalla2IngHora_screen_init(void);
lv_obj_t * ui_Pantalla2IngHora;
lv_obj_t * ui_TextoIngHora;
lv_obj_t * ui_RodilloHora;
lv_obj_t * ui_RodilloMinuto;
lv_obj_t * ui_TextoHora;
lv_obj_t * ui_TextoMinuto;
void ui_event_BotonOK(lv_event_t * e);
lv_obj_t * ui_BotonOK;
lv_obj_t * ui_EtiquetaOK;
lv_obj_t * ui_Bar2;

// SCREEN: ui_Pantalla3VisuHora
void ui_Pantalla3VisuHora_screen_init(void);
lv_obj_t * ui_Pantalla3VisuHora;
lv_obj_t * ui_Hora;
lv_obj_t * ui_Min;
lv_obj_t * ui_Puntos;
void ui_event_Menu(lv_event_t * e);
lv_obj_t * ui_Menu;
lv_obj_t * ui_Menu1;
void ui_event_Alarm(lv_event_t * e);
lv_obj_t * ui_Alarm;
lv_obj_t * ui_LabAlarm;

// SCREEN: ui_Pantalla4Menu
void ui_Pantalla4Menu_screen_init(void);
lv_obj_t * ui_Pantalla4Menu;
void ui_event_ConfigHora(lv_event_t * e);
lv_obj_t * ui_ConfigHora;
lv_obj_t * ui_TConfigHora;
void ui_event_ConfigAlarm(lv_event_t * e);
lv_obj_t * ui_ConfigAlarm;
lv_obj_t * ui_TconfigAlarm;
void ui_event_AtrasMenu(lv_event_t * e);
lv_obj_t * ui_AtrasMenu;
lv_obj_t * ui_Label5;

// SCREEN: ui_Pantalla5ConfigAlarmas
void ui_Pantalla5ConfigAlarmas_screen_init(void);
lv_obj_t * ui_Pantalla5ConfigAlarmas;
lv_obj_t * ui_TabAlarm;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Label3;
void ui_event_RodAlarm(lv_event_t * e);
lv_obj_t * ui_RodAlarm;
void ui_event_OkAlarm(lv_event_t * e);
lv_obj_t * ui_OkAlarm;
lv_obj_t * ui_LabelOK;

// SCREEN: ui_Pantalla6VisuAlarm
void ui_Pantalla6VisuAlarm_screen_init(void);
lv_obj_t * ui_Pantalla6VisuAlarm;
lv_obj_t * ui_LabAlarSel[5];
lv_obj_t * ui_TextArea3;
void ui_event_AtrasAlarm(lv_event_t * e);
lv_obj_t * ui_AtrasAlarm;
lv_obj_t * ui_Label4;
lv_obj_t * ui____initial_actions0;
lv_obj_t *tabla; 
const lv_img_dsc_t *ui_imgset_mushu_5[1] = {&ui_img_mushu3_5_png};
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Pantalla1Bienvenido(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Pantalla2IngHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_Pantalla2IngHora_screen_init);
        _ui_screen_delete(&ui_Pantalla1Bienvenido);
    }
}
void ui_event_TextoBienvenido(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_screen_change(&ui_Pantalla2IngHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 5000, &ui_Pantalla2IngHora_screen_init);
    }
}
/*void ui_event_BotonOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_set_property(ui_Bar2, _UI_BAR_PROPERTY_VALUE_WITH_ANIM, 100);
        _ui_screen_delete(&ui_Pantalla2IngHora);
        _ui_screen_change(&ui_Pantalla3VisuHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla3VisuHora_screen_init);
    }
}*/
void ui_event_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla3VisuHora);
        _ui_screen_change(&ui_Pantalla4Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla4Menu_screen_init);
    }
}
void ui_event_Alarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla3VisuHora);
        _ui_screen_change(&ui_Pantalla6VisuAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla6VisuAlarm_screen_init);        
    }
}
void ui_event_ConfigHora(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla4Menu);
        _ui_screen_change(&ui_Pantalla2IngHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla2IngHora_screen_init);
    }
}
void ui_event_ConfigAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla4Menu);
        _ui_screen_change(&ui_Pantalla5ConfigAlarmas, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla5ConfigAlarmas_screen_init);
    }
}
void ui_event_AtrasMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla4Menu);
        _ui_screen_change(&ui_Pantalla3VisuHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla3VisuHora_screen_init);
    }
}
/*void ui_event_RodAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_Label2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}*/
/*void ui_event_OkAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla5ConfigAlarmas);
        _ui_screen_change(&ui_Pantalla6VisuAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla6VisuAlarm_screen_init);
    }
}*/


void ui_event_AtrasAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Pantalla6VisuAlarm);
        _ui_screen_change(&ui_Pantalla3VisuHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla3VisuHora_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Pantalla1Bienvenido_screen_init();
    ui_Pantalla2IngHora_screen_init();
    ui_Pantalla3VisuHora_screen_init();
    ui_Pantalla4Menu_screen_init();
    ui_Pantalla5ConfigAlarmas_screen_init();
    ui_Pantalla6VisuAlarm_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Pantalla1Bienvenido);
}
