// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#ifndef _PANTALLA1_UI_H
#define _PANTALLA1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include <stdio.h>
// SCREEN: ui_Pantalla1Bienvenido
void ui_Pantalla1Bienvenido_screen_init(void);
void ui_event_Pantalla1Bienvenido(lv_event_t * e);
extern lv_obj_t * ui_Pantalla1Bienvenido;
void ui_event_TextoBienvenido(lv_event_t * e);
extern lv_obj_t * ui_TextoBienvenido;
// SCREEN: ui_Pantalla2IngHora
void ui_Pantalla2IngHora_screen_init(void);
extern lv_obj_t * ui_Pantalla2IngHora;
extern lv_obj_t * ui_TextoIngHora;
extern lv_obj_t * ui_RodilloHora;
extern lv_obj_t * ui_RodilloMinuto;
extern lv_obj_t * ui_TextoHora;
extern lv_obj_t * ui_TextoMinuto;
void ui_event_BotonOK(lv_event_t * e);
extern lv_obj_t * ui_BotonOK;
extern lv_obj_t * ui_EtiquetaOK;
extern lv_obj_t * ui_Bar2;
// SCREEN: ui_Pantalla3VisuHora
void ui_Pantalla3VisuHora_screen_init(void);
extern lv_obj_t * ui_Pantalla3VisuHora;
extern lv_obj_t * ui_Hora;
extern lv_obj_t * ui_Min;
extern lv_obj_t * ui_Puntos;
void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_Menu1;
void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_LabAlarm;
// SCREEN: ui_Pantalla4Menu
void ui_Pantalla4Menu_screen_init(void);
extern lv_obj_t * ui_Pantalla4Menu;
void ui_event_ConfigHora(lv_event_t * e);
extern lv_obj_t * ui_ConfigHora;
extern lv_obj_t * ui_TConfigHora;
void ui_event_ConfigAlarm(lv_event_t * e);
extern lv_obj_t * ui_ConfigAlarm;
extern lv_obj_t * ui_TconfigAlarm;
void ui_event_AtrasMenu(lv_event_t * e);
extern lv_obj_t * ui_AtrasMenu;
extern lv_obj_t * ui_Label5;
// SCREEN: ui_Pantalla5ConfigAlarmas
void ui_Pantalla5ConfigAlarmas_screen_init(void);
extern lv_obj_t * ui_Pantalla5ConfigAlarmas;
extern lv_obj_t * ui_TabAlarm;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Label3;
void ui_event_RodAlarm(lv_event_t * e);
extern lv_obj_t * ui_RodAlarm;
//void ui_event_OkAlarm(lv_event_t * e);
extern lv_obj_t * ui_OkAlarm;
extern lv_obj_t * ui_LabelOK;
// SCREEN: ui_Pantalla6VisuAlarm
void ui_Pantalla6VisuAlarm_screen_init(void);
extern lv_obj_t * ui_Pantalla6VisuAlarm;
extern lv_obj_t * ui_LabAlarSel;
extern lv_obj_t * ui_TextArea3;
void ui_event_AtrasAlarm(lv_event_t * e);
extern lv_obj_t * ui_AtrasAlarm;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;
//extern lv_obj_t *pestanas[10]; //Para el número de pestañas de las alarmas
//extern lv_obj_t *rollerS[3]; //1er Rodillo del tabview
//extern lv_obj_t *rollerS1[3]; //2do Rodillo del tabview

void ui_init(void);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
