// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#include "ui.h"

void ui_Pantalla4Menu_screen_init(void)
{
    ui_Pantalla4Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pantalla4Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Pantalla4Menu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Pantalla4Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Pantalla4Menu, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pantalla4Menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pantalla4Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pantalla4Menu, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigHora = lv_btn_create(ui_Pantalla4Menu);
    lv_obj_set_width(ui_ConfigHora, 136);
    lv_obj_set_height(ui_ConfigHora, 52);
    lv_obj_set_x(ui_ConfigHora, -2);
    lv_obj_set_y(ui_ConfigHora, -60);
    lv_obj_set_align(ui_ConfigHora, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigHora, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigHora, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigHora, lv_color_hex(0x31B9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TConfigHora = lv_label_create(ui_ConfigHora);
    lv_obj_set_width(ui_TConfigHora, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TConfigHora, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TConfigHora, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TConfigHora, "CONFIG HORA");
    lv_obj_set_style_text_color(ui_TConfigHora, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TConfigHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TConfigHora, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigAlarm = lv_btn_create(ui_Pantalla4Menu);
    lv_obj_set_width(ui_ConfigAlarm, 136);
    lv_obj_set_height(ui_ConfigAlarm, 50);
    lv_obj_set_x(ui_ConfigAlarm, -3);
    lv_obj_set_y(ui_ConfigAlarm, 15);
    lv_obj_set_align(ui_ConfigAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigAlarm, lv_color_hex(0x31B9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TconfigAlarm = lv_label_create(ui_ConfigAlarm);
    lv_obj_set_width(ui_TconfigAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TconfigAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TconfigAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TconfigAlarm, "CONFIG ALARMA");
    lv_obj_set_style_text_color(ui_TconfigAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TconfigAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TconfigAlarm, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AtrasMenu = lv_btn_create(ui_Pantalla4Menu);
    lv_obj_set_width(ui_AtrasMenu, 64);
    lv_obj_set_height(ui_AtrasMenu, 34);
    lv_obj_set_x(ui_AtrasMenu, -107);
    lv_obj_set_y(ui_AtrasMenu, 75);
    lv_obj_set_align(ui_AtrasMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AtrasMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AtrasMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AtrasMenu, lv_color_hex(0xE64242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AtrasMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AtrasMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AtrasMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AtrasMenu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_AtrasMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AtrasMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_AtrasMenu);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "ATRAS");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConfigHora, ui_event_ConfigHora, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfigAlarm, ui_event_ConfigAlarm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AtrasMenu, ui_event_AtrasMenu, LV_EVENT_ALL, NULL);

}
