// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#include "ui.h"
#include "Main_Screen.h"
#include "ds3231.h"

extern uint8_t u8_TimeConfigDone;

//extern void Time_config_touch(tm_t * const _time, uint8_t _hour,uint8_t _minute );
extern struct tm time_tc;
//extern uint8_t u8_hour;
//extern uint8_t u8_min;
uint8_t u8_hour;
uint8_t u8_min;
extern i2c_dev_t s_dev; // necessary for RTC_init()


void ui_event_BotonOK(lv_event_t * e)
{
    
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        char buf[32];
        char buf1[32];
        // Obtiene el valor actual del rodillo
        //const char *selected_option = lv_roller_get_selected_str(roller, buf, sizeof(buf));
        lv_roller_get_selected_str(ui_RodilloHora, buf, sizeof(buf));
        lv_roller_get_selected_str(ui_RodilloMinuto, buf1, sizeof(buf1));
        printf("Número seleccionado: %s\n", buf);
        printf("Número seleccionado 2: %s\n", buf1);
        u8_hour = (uint8_t)atoi(buf);
        u8_min = (uint8_t)atoi(buf1); 
        Time_config_touch(&time_tc,u8_hour, u8_min ); //Aqui se rellena la estructura time con la hora
        printf("Hora: %d\n", time_tc.tm_hour);
        printf("minuto: %d\n", time_tc.tm_min);
        u8_TimeConfigDone=1;
        ESP_ERROR_CHECK(ds3231_set_time(&s_dev, &time_tc)); // Se envia la hora al modulo

        _ui_bar_set_property(ui_Bar2, _UI_BAR_PROPERTY_VALUE_WITH_ANIM, 100);
        _ui_screen_delete(&ui_Pantalla2IngHora);
        _ui_screen_change(&ui_Pantalla3VisuHora, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla3VisuHora_screen_init);
    }
}


void ui_Pantalla2IngHora_screen_init(void)
{
    ui_Pantalla2IngHora = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pantalla2IngHora, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_Pantalla2IngHora, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pantalla2IngHora, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pantalla2IngHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pantalla2IngHora, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextoIngHora = lv_textarea_create(ui_Pantalla2IngHora);
    lv_obj_set_width(ui_TextoIngHora, 175);
    lv_obj_set_height(ui_TextoIngHora, 40);
    lv_obj_set_x(ui_TextoIngHora, 5);
    lv_obj_set_y(ui_TextoIngHora, -80);
    lv_obj_set_align(ui_TextoIngHora, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextoIngHora, "INGRESAR HORA");
    lv_textarea_set_placeholder_text(ui_TextoIngHora, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextoIngHora, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextoIngHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextoIngHora, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextoIngHora, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextoIngHora, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextoIngHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextoIngHora, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextoIngHora, lv_color_hex(0x808080), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextoIngHora, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);


    /*-----------------------------RODILLOS--------------------------------------*/
    ui_RodilloHora = lv_roller_create(ui_Pantalla2IngHora);
    lv_roller_set_options(ui_RodilloHora,
                          "0\n1\n2\n3\n4\n5\n6\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_RodilloHora, 100);
    lv_obj_set_width(ui_RodilloHora, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RodilloHora, -100);
    lv_obj_set_y(ui_RodilloHora, 40);
    lv_obj_set_align(ui_RodilloHora, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_RodilloHora, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RodilloHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RodilloHora, lv_color_hex(0xFF0000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RodilloHora, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);



    ui_RodilloMinuto = lv_roller_create(ui_Pantalla2IngHora);
    lv_roller_set_options(ui_RodilloMinuto,
                          "0\n1\n2\n3\n4\n5\n6\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_RodilloMinuto, 100);
    lv_obj_set_width(ui_RodilloMinuto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RodilloMinuto, -8);
    lv_obj_set_y(ui_RodilloMinuto, 40);
    lv_obj_set_align(ui_RodilloMinuto, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_RodilloMinuto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RodilloMinuto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RodilloMinuto, lv_color_hex(0xF90505), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RodilloMinuto, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RodilloMinuto, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RodilloMinuto, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    /*-----------------------------------------------------------------------*/


    ui_TextoHora = lv_textarea_create(ui_Pantalla2IngHora);
    lv_obj_set_width(ui_TextoHora, 63);
    lv_obj_set_height(ui_TextoHora, 38);
    lv_obj_set_x(ui_TextoHora, -100);
    lv_obj_set_y(ui_TextoHora, -30);
    lv_obj_set_align(ui_TextoHora, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextoHora, "HORA");
    lv_textarea_set_placeholder_text(ui_TextoHora, "Placeholder...");

    ui_TextoMinuto = lv_textarea_create(ui_Pantalla2IngHora);
    lv_obj_set_width(ui_TextoMinuto, 48);
    lv_obj_set_height(ui_TextoMinuto, 38);
    lv_obj_set_x(ui_TextoMinuto, -8);
    lv_obj_set_y(ui_TextoMinuto, -30);
    lv_obj_set_align(ui_TextoMinuto, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextoMinuto, "MIN");
    lv_textarea_set_placeholder_text(ui_TextoMinuto, "Placeholder...");

    ui_BotonOK = lv_btn_create(ui_Pantalla2IngHora);
    lv_obj_set_width(ui_BotonOK, 65);
    lv_obj_set_height(ui_BotonOK, 40);
    lv_obj_set_x(ui_BotonOK, 98);
    lv_obj_set_y(ui_BotonOK, 34);
    lv_obj_set_align(ui_BotonOK, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BotonOK, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BotonOK, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BotonOK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BotonOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonOK, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EtiquetaOK = lv_label_create(ui_BotonOK);
    lv_obj_set_width(ui_EtiquetaOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EtiquetaOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EtiquetaOK, 78);
    lv_obj_set_y(ui_EtiquetaOK, 28);
    lv_obj_set_align(ui_EtiquetaOK, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EtiquetaOK, "OK");
    lv_obj_set_style_text_color(ui_EtiquetaOK, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EtiquetaOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EtiquetaOK, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EtiquetaOK, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_Pantalla2IngHora);
    lv_bar_set_value(ui_Bar2, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 64);
    lv_obj_set_height(ui_Bar2, 23);
    lv_obj_set_x(ui_Bar2, 97);
    lv_obj_set_y(ui_Bar2, -13);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_BotonOK, ui_event_BotonOK, LV_EVENT_ALL, NULL);

}
