// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#include "ui.h"
#include "Main_Screen.h"
#include "ds3231.h"

extern struct tm time_tc;
extern i2c_dev_t s_dev; // necessary for RTC_init()


void ui_Pantalla3VisuHora_screen_init(void)
{
    /*while (1)
    {
        if (ds3231_get_time(&s_dev, &time_tc) != ESP_OK)
        {
             printf("Could not get time\n");
        }
        vTaskDelay(pdMS_TO_TICKS(1000));
        lv_timer_handler();
        printf("--- VISUALIZAR ---\n");
        printf("%02d:%02d:%02d\n", time_tc.tm_hour, time_tc.tm_min, time_tc.tm_sec);
    }*/
    
    ui_Pantalla3VisuHora = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pantalla3VisuHora, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src( ui_Pantalla3VisuHora, &ui_img_mushu3_5_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_img_opa(ui_Pantalla3VisuHora, 210, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Pantalla3VisuHora, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pantalla3VisuHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pantalla3VisuHora, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pantalla3VisuHora, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hora = lv_label_create(ui_Pantalla3VisuHora);
    lv_obj_set_width(ui_Hora, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hora, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hora, -39);
    lv_obj_set_y(ui_Hora, -9);
    //lv_obj_set_align(ui_Hora, LV_ALIGN_RIGHT_MID);
    lv_obj_align(ui_Hora, LV_ALIGN_CENTER, 5, -10);
    //lv_label_set_text(ui_Hora, "10");  Esto lo estoy imprimiendo en el main principal
    lv_obj_set_style_text_font(ui_Hora, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Min = lv_label_create(ui_Pantalla3VisuHora);
    // lv_obj_set_width(ui_Min, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Min, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_Min, 45);
    // lv_obj_set_y(ui_Min, -11);
    // lv_obj_set_align(ui_Min, LV_ALIGN_CENTER);
    // //lv_label_set_text(ui_Min, "59");  Esto lo estoy imprimiendo en el main principal

    // ui_Puntos = lv_label_create(ui_Pantalla3VisuHora);
    // lv_obj_set_width(ui_Puntos, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Puntos, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_Puntos, 0);
    // lv_obj_set_y(ui_Puntos, -13);
    // lv_obj_set_align(ui_Puntos, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Puntos, ":");

    ui_Menu = lv_btn_create(ui_Pantalla3VisuHora);
    lv_obj_set_width(ui_Menu, 88);
    lv_obj_set_height(ui_Menu, 27);
    lv_obj_set_x(ui_Menu, -79);
    lv_obj_set_y(ui_Menu, 70);
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0xE64242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Menu, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu1 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Menu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Menu1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu1, "MENU");
    lv_obj_set_style_text_color(ui_Menu1, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Menu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Menu1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Menu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Menu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm = lv_btn_create(ui_Pantalla3VisuHora);
    lv_obj_set_width(ui_Alarm, 92);
    lv_obj_set_height(ui_Alarm, 27);
    lv_obj_set_x(ui_Alarm, 86);
    lv_obj_set_y(ui_Alarm, 69);
    lv_obj_set_align(ui_Alarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm, lv_color_hex(0xE64242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Alarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Alarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Alarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabAlarm = lv_label_create(ui_Alarm);
    lv_obj_set_width(ui_LabAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabAlarm, 1);
    lv_obj_set_y(ui_LabAlarm, 1);
    lv_obj_set_align(ui_LabAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabAlarm, "ALARMAS");
    lv_obj_set_style_text_font(ui_LabAlarm, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);

}
