// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#include "ui.h"

void ui_Pantalla1Bienvenido_screen_init(void)
{
    ui_Pantalla1Bienvenido = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pantalla1Bienvenido, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_Pantalla1Bienvenido, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pantalla1Bienvenido, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pantalla1Bienvenido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pantalla1Bienvenido, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextoBienvenido = lv_textarea_create(ui_Pantalla1Bienvenido);
    lv_obj_set_width(ui_TextoBienvenido, 300);
    lv_obj_set_height(ui_TextoBienvenido, 70);
    lv_obj_set_align(ui_TextoBienvenido, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextoBienvenido, "BIENVENIDO!");
    lv_textarea_set_placeholder_text(ui_TextoBienvenido, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextoBienvenido, lv_color_hex(0xCF1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextoBienvenido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextoBienvenido, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextoBienvenido, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextoBienvenido, lv_color_hex(0xF70909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextoBienvenido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextoBienvenido, ui_event_TextoBienvenido, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pantalla1Bienvenido, ui_event_Pantalla1Bienvenido, LV_EVENT_ALL, NULL);

}
