// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: Pantalla1

#include "ui.h"
#include "ui_helpers.h"
#include "Main_Screen.h"


lv_obj_t *rollerS[5]; //1er Rodillo del tabview
lv_obj_t *rollerS1[5]; //2do Rodillo del tabview
lv_obj_t *pestanas[10]; //Para el número de pestañas de las alarmas
int valor_rodillo=1;
char buf[32];
char buf1[32];

uint8_t u8_hour_A;
uint8_t u8_min_A;
extern tm_t s_alarmas_manual[];

char row_name[16]; //Nombre de las filas
char row_name1[16]; //Nombre de las filas


void ui_event_OkAlarm(lv_obj_t *e)
{       
    char u8_timeconverted_1[9];  
    char u8_timeconverted_2[9];    
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    //lv_obj_t * button = lv_event_get_target(e);
    if (code == LV_EVENT_CLICKED) {

        for (size_t i = 0; i < valor_rodillo; i++)
        {
            lv_roller_get_selected_str(rollerS[i], buf, sizeof(buf));
            lv_roller_get_selected_str(rollerS1[i], buf1, sizeof(buf1));
            // Imprime el valor actual en pantalla (puedes personalizar cómo lo haces)
            printf("Valor del rodillo %d: %s\n", i, buf);
            printf("Valor del rodillo %d: %s\n", i, buf1);

            u8_hour_A = (uint8_t)atoi(buf);
            u8_min_A = (uint8_t)atoi(buf1);

            Time_config_touch(&s_alarmas_manual[i],u8_hour_A, u8_min_A ); //Aqui se rellena la estructura time con la hora

            convertTime2StringDisplay(&s_alarmas_manual[i],u8_timeconverted_1);

             // Establecemos las alarmas en las filas en la tabla de la pantalla 6
            //snprintf(row_name, sizeof(row_name), "%d : %d", u8_hour_A, u8_min_A);
            lv_table_set_cell_value(tabla, i, 1, u8_timeconverted_1); //Colocamos en la columna 1 lo concerniente a las alarmas hora

            snprintf(row_name1, sizeof(row_name1), "%s %d", "Alarma", i+1);
            lv_table_set_cell_value(tabla, i, 0, row_name1); //Colocamos en la columna 0 lo concerniente al nombre alarma "X"

            _ui_screen_delete(&ui_Pantalla5ConfigAlarmas);
            _ui_screen_change(&ui_Pantalla6VisuAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pantalla6VisuAlarm_screen_init);
        }        
    }
}

void actualizar_pantalla(int num_pestanas) {

    // Eliminar las pestañas existentes
    for (int i = 0; i < 5; i++) {
        if (pestanas[i]) {
            lv_obj_del(pestanas[i]);
            pestanas[i] = NULL;
        }
    }

    // Crear las nuevas pestañas
    for (int i = 0; i < num_pestanas; i++) {
        char nombre_pestaña[20];
        snprintf(nombre_pestaña, sizeof(nombre_pestaña), "P %d", i + 1);
        pestanas[i] = lv_tabview_add_tab(ui_TabAlarm, nombre_pestaña);


        rollerS[i] = lv_roller_create(pestanas[i]);
        lv_roller_set_options(rollerS[i], "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_INFINITE);
        lv_roller_set_visible_row_count(rollerS[i], 3);
        lv_obj_set_width(rollerS[i], 50);
        lv_obj_align(rollerS[i], LV_ALIGN_OUT_BOTTOM_LEFT, 20, 5);

        rollerS1[i] = lv_roller_create(pestanas[i]);
        lv_roller_set_options(rollerS1[i], "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_INFINITE);
        lv_roller_set_visible_row_count(rollerS1[i], 3);
        lv_obj_set_width(rollerS1[i], 50);
        lv_obj_align(rollerS1[i], LV_ALIGN_OUT_BOTTOM_LEFT, 100, 5);

        // Personaliza el contenido de la pestaña según tus necesidades
        /*lv_obj_t *label = lv_label_create(pestanas[i]);
        lv_label_set_text(label, "Contenido de la pestaña");*/


        /*ui_LabAlarSel[i] = lv_label_create(ui_Pantalla6VisuAlarm);
        lv_obj_set_width(ui_LabAlarSel[i], LV_SIZE_CONTENT);   /// 1
        lv_obj_set_height(ui_LabAlarSel[i], LV_SIZE_CONTENT);    /// 1
        lv_obj_set_x(ui_LabAlarSel[i], 0);
        lv_obj_set_y(ui_LabAlarSel[i], -75);
        lv_obj_set_align(ui_LabAlarSel[i], LV_ALIGN_CENTER);*/



    }
}

void ui_event_RodAlarm(lv_event_t * e)
{
 lv_event_code_t event = lv_event_get_code(e);

    if (event == LV_EVENT_VALUE_CHANGED) {

        lv_roller_get_selected_str(ui_RodAlarm, buf, sizeof(buf));
        printf("Número seleccionado: %s\n", buf);
        valor_rodillo = atoi(buf);
        actualizar_pantalla(valor_rodillo);

        lv_table_set_row_cnt(tabla, valor_rodillo); //Establecemos el # de las filas de la tabla de la pantalla 6 en función del rodillo
    }
}


void ui_Pantalla5ConfigAlarmas_screen_init(void)
{
    ui_Pantalla5ConfigAlarmas = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pantalla5ConfigAlarmas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Pantalla5ConfigAlarmas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pantalla5ConfigAlarmas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pantalla5ConfigAlarmas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabAlarm = lv_tabview_create(ui_Pantalla5ConfigAlarmas, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabAlarm, 220);
    lv_obj_set_height(ui_TabAlarm, 166);
    lv_obj_set_x(ui_TabAlarm, 32);
    lv_obj_set_y(ui_TabAlarm, -10);
    lv_obj_set_align(ui_TabAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_RodAlarm = lv_roller_create(ui_Pantalla5ConfigAlarmas);
    lv_roller_set_options(ui_RodAlarm, "1\n2\n3\n4\n5", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_RodAlarm, 94);
    lv_obj_set_width(ui_RodAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RodAlarm, -127);
    lv_obj_set_y(ui_RodAlarm, -44);
    lv_obj_set_align(ui_RodAlarm, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_RodAlarm, LV_STATE_CHECKED);       /// States

    ui_OkAlarm = lv_btn_create(ui_Pantalla5ConfigAlarmas);
    lv_obj_set_width(ui_OkAlarm, 61);
    lv_obj_set_height(ui_OkAlarm, 50);
    lv_obj_set_x(ui_OkAlarm, -122);
    lv_obj_set_y(ui_OkAlarm, 55);
    lv_obj_set_align(ui_OkAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OkAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OkAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOK = lv_label_create(ui_OkAlarm);
    lv_obj_set_width(ui_LabelOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOK, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOK, "OK");

    lv_obj_add_event_cb(ui_RodAlarm, ui_event_RodAlarm, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_OkAlarm, ui_event_OkAlarm, LV_EVENT_ALL, NULL);

    actualizar_pantalla(1);  // Inicialmente, muestra 1 pestaña
}
